### PR TITLE
Add dev container, clab and more

### PR DESCRIPTION
**Pull request by ankudinov**
Some improvements for a better hackathon experience.

### CODE REVIEW

**Comment by titom73** [comment]
Thanks @ankudinov for this PR. Seems really nice.
Could you add a `md` file to describe how to use it under `docs/` folder ? It would help user to leverage this approach.

Thanks for contributing

**Comment by ankudinov** [comment]
@titom73 added a slide explaining how to use. I think that's enough. We'll be in one room and if someone will pick this option - they know what to do.

**Comment by ankudinov** [comment]
To push containers successfully actions must have write permissions and packages must be writable for account/org (normally packages settings are inherited from repo).

**Review by titom73 — APPROVED** [review]
LGTM! Thanks for contributing.

To make it easier to consume, we will merge into a dedicated branch with a reference in main readme

**Pull request merged**
